INSERT INTO `bookcategory` (`id`, `name`) VALUES (1, '历史');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (2, '哲学');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (3, '艺术');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (4, '推理');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (5, '言情');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (6, '职场');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (7, '美食');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (8, '教育');
INSERT INTO `bookcategory` (`id`, `name`) VALUES (9, '科普');
